[package]
name = "ngxora-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
ngxora-compile = { path = "../ngxora-compile" }
pingora = { version = "0.7.0", features = ["lb"] }
pingora-proxy = { version = "0.7.0" }
